<a href="https://colab.research.google.com/github/Sha-98/Data-Science-Masters/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Assignment**

## **Consider the below code to answer further questions:**



In [8]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## **Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**


 In Python, a list is a built-in data type, while an array might be created using a library like NumPy. So, Yes, there can be a difference in the data type of variables list_ and array_list if they are created using different methods.

 A simple code snippet to print the data types of both variables is as follows:

In [17]:
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [18]:
array_l = np.array([1, 2, 3, 4, 5])
# print("Data type of array_list:", array_list)
array_l

array([1, 2, 3, 4, 5])

In [19]:
print("Data type of array_list with list_ :", type(array_list))
print("Data type of array_list with np.array:", type(array_l))

Data type of array_list with list_ : <class 'numpy.ndarray'>
Data type of array_list with np.array: <class 'numpy.ndarray'>


* **array(['1', '2', '3', '4', '5'], dtype='<U1'):** In this case, the elements inside the array are represented as strings, not integers. Notice the quotes around each element ('1', '2', '3', '4', '5'). This happens when you create an array with elements defined as strings, as we did for our variable ***array_list***

* **array([1, 2, 3, 4, 5]):** In this case, the elements inside the array are represented as integers. This is the typical behavior when you create an array with elements defined as integers, as we did for variable ***array_l***

***If we want the elements to be treated as integers, make sure you provide them without quotes when creating the array. If we provide them as strings, the array will consider them as string data.***

## **Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.**


In [21]:
for i in array_list:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [22]:
for i in array_l:
  print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## **Q3. Considering the following changes in the variable, array_list:**


In [23]:
array_list = np.array(object = list_, dtype = int)

**Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.**

In [24]:
for i in array_list:
  print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [25]:
for i in array_l:
  print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As observed, now the data type of each element for both the array is int64. This is because we changes the data type of elements of *array_list*.

## ***Consider the below code to answer further questions:***

In [26]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [27]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

## **Q4. Write a code to find the following characteristics of variable, num_array:**

**(i) shape**
**(ii) size**


In [28]:
num_array.shape

(2, 3)

In [29]:
num_array.size

6

## **Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.**

**[Hint: The size of the array will be 9 and the shape will be (3,3).]**


In [30]:
zero_matrix = np.zeros((3, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## **Q6. Create an identity matrix of shape (5,5) using numpy functions?**

**[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [31]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])